services:
  bot:
    container_name: heli
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      loki: http://localhost:3100
    networks:
      - loki
    depends_on:
      loki:
        condition: service_healthy
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    healthcheck:
      test: wget -q --tries=1 -O- http://localhost:3100/ready
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - ../Configs/loki-config.yml:/etc/loki/config.yml
    networks:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ../grafana_data:/var/lib/grafana
    depends_on:
      loki:
        condition: service_healthy
    networks:
      - loki
    restart: unless-stopped


  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ../Configs/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      loki:
        condition: service_healthy
    networks:
      - loki
    restart: unless-stopped

networks:
  loki:
    name: loki
    driver: bridge

volumes:
  grafana_data: