services:
  bot:
    build:
      context: ..
      dockerfile: Dockerfile
    networks:
      - loki
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ../configs/loki-config.yml:/etc/loki/config.yml
    networks:
      - loki
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ../grafana_data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - loki
    restart: unless-stopped
        

  # promtail:
  #   image: grafana/promatail:latest
  #   container_name: promtail
  #   volumes: 
  #     - ../Configs/promatail-config.yml
  #     - /var/log:/var/log
  #   command: -config.file=/etc/promtail/config.yml
  #   depends_on:
  #     - loki
  #   restart: unless-stopped
networks:
  loki:
    name: loki
    driver: bridge

volumes:
  grafana_data: