services:
  bot:
    build:
      context: ..
      dockerfile: Dockerfile
  elasticsearch:
      image: elasticsearch:8.14.3
      container_name: elasticsearch
      environment: 
        - discovery.type=single-node
        - xpack.security.enabled=false
      ports:
        - "9200:9200"
  logstash:
    image: logstash:8.14.3
    container_name: logstash
    volumes: 
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on: 
      - elasticsearch
  kibana:
    image: kibana:8.14.3
    container_name: kibana
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
    - "5601:5601"
    depends_on: 
    - elasticsearch

