# services:
#     bot:
#         build:
#             context: ..
#             dockerfile: Dockerfile
version: '3.8'

services:
  bot:
    build:
      context: ..
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2g"
        reservations:
          cpus: "1" 
          memory: "1g" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: bot-container
    cpu_count: 2
    mem_limit: 2g 
    restart: unless-stopped
